test:
	  xcodebuild test
	    -sdk iphonesimulator
	    -project App.xcodeproj
	    -scheme "AppTests"
	    -configuration "Debug"
	    -destination platform="iOS Simulator,name=iPhone 12 Pro,OS=15.0" 
	    -resultBundlePath ResultBundle
